/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.MenuControl;
import control.PembeliControl;
import control.PesananControl;
import control.DetailPesananControl;
import exception.InputanKosongException;
import exception.NegativeInputException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Menu;
import model.TempMenu;
import model.DetailPesanan;
import model.Pegawai;
import model.Pembeli;
import model.Pesanan;

import table.TableMenu;
import table.TableTempMenu;

public class PesananView extends javax.swing.JFrame {
    private int count=0;
    private MenuControl mc;
    private PembeliControl pembeliControl;
    private PesananControl pesananControl;
    private Pegawai pegawai;
    private DetailPesananControl detailControl;
    private int id_pegawai =1;
    String action = null;
    List<Menu> listMenu;
    List<TempMenu> tempListMenu = new ArrayList<>();
    
    
    
    public PesananView() {
        initComponents();
        mc = new MenuControl();
        pembeliControl = new PembeliControl();
        pesananControl = new PesananControl();
        detailControl = new DetailPesananControl();
        showMenu();
        clearText();
        
    }
    
    public PesananView(Pegawai pegawai) {
        initComponents();
        mc = new MenuControl();
        pembeliControl = new PembeliControl();
        pesananControl = new PesananControl();
        detailControl = new DetailPesananControl();
        this.pegawai = pegawai;
        showMenu();
        clearText();
        setComponent(false);
        
    }
    
    public void showMenu(){
        tblMenu.setModel(mc.showDataMenu(""));
        tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
    }
    
    public void setComponent(boolean value){
        bnyakPesananInputField.setEnabled(value);
        tambahBtn.setEnabled(value);
        batalBtn1.setEnabled(value);
        tambahPesananBtn.setEnabled(value);
        hapusPesananBtn.setEnabled(value);
        batalBtn2.setEnabled(value);
    }
    
    public void clearText(){
        namaMenuField.setText("");
        hargaMenuField.setText("");
        deskripsiMenuField.setText("");
        bnyakPesananInputField.setText("");
        namaPembeliInput.setText("");
        nomorHPInput.setText("");
        tanggalTransaksiInput.setText("");
    }
    
    public void clearInputMenu(){
        namaMenuField.setText("");
        hargaMenuField.setText("");
        deskripsiMenuField.setText("");
        bnyakPesananInputField.setText("");
    }
    
    public void InputanKosongException() throws InputanKosongException{
        if(namaPembeliInput.getText().isEmpty() 
                    || nomorHPInput.getText().isEmpty() || tanggalTransaksiInput.getText().isEmpty()) {
            throw new InputanKosongException();
        }
    }
    
    public void NegativeInputException() throws NegativeInputException {
        if( Integer.parseInt(bnyakPesananInputField.getText()) <= 0){
            throw new NegativeInputException();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelRound1 = new view.PanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTempMenu = new javax.swing.JTable();
        tambahPesananBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        batalBtn2 = new javax.swing.JButton();
        hapusPesananBtn = new javax.swing.JButton();
        panelRound2 = new view.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        namaPembeliInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomorHPInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tanggalTransaksiInput = new javax.swing.JTextField();
        panelRound4 = new view.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tambahBtn = new javax.swing.JButton();
        batalBtn1 = new javax.swing.JButton();
        panelRound3 = new view.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deskripsiMenuField = new javax.swing.JTextArea();
        hargaMenuField = new javax.swing.JTextField();
        namaMenuField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bnyakPesananInputField = new javax.swing.JTextField();
        editMenuPanel = new view.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        LabelPembeli = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editMenuLabel = new javax.swing.JLabel();
        riwayatPesananLabel = new javax.swing.JLabel();
        panelRound5 = new view.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(242, 217, 99));
        mainPanel.setForeground(new java.awt.Color(0, 0, 0));

        panelRound1.setBackground(new java.awt.Color(81, 175, 157));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        tblTempMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTempMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTempMenuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTempMenu);

        tambahPesananBtn.setText("Tambah Pesanan");
        tambahPesananBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPesananBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(252, 233, 201));
        jLabel10.setText("Pesanan Sementara");

        batalBtn2.setText("batal");
        batalBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtn2ActionPerformed(evt);
            }
        });

        hapusPesananBtn.setText("Hapus Pesanan");
        hapusPesananBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPesananBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tambahPesananBtn)
                .addGap(18, 18, 18)
                .addComponent(batalBtn2)
                .addGap(10, 10, 10))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hapusPesananBtn)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusPesananBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahPesananBtn)
                    .addComponent(batalBtn2))
                .addGap(18, 18, 18))
        );

        panelRound2.setBackground(new java.awt.Color(48, 81, 90));
        panelRound2.setRoundBottomLeft(15);
        panelRound2.setRoundBottomRight(15);
        panelRound2.setRoundTopLeft(15);
        panelRound2.setRoundTopRight(15);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 233, 201));
        jLabel1.setText("NamaPembeli");

        namaPembeliInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPembeliInputActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 233, 201));
        jLabel2.setText("Nomor HP");

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 233, 201));
        jLabel3.setText("Tanggal Transaksi");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tanggalTransaksiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nomorHPInput, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(namaPembeliInput, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaPembeliInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomorHPInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tanggalTransaksiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelRound4.setBackground(new java.awt.Color(81, 175, 157));
        panelRound4.setForeground(new java.awt.Color(89, 108, 118));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);

        tblMenu.setBackground(new java.awt.Color(48, 81, 90));
        tblMenu.setForeground(new java.awt.Color(48, 81, 90));
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        jLabel4.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 81, 90));
        jLabel4.setText("MENU");

        tambahBtn.setBackground(new java.awt.Color(243, 161, 97));
        tambahBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        tambahBtn.setForeground(new java.awt.Color(48, 81, 90));
        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        batalBtn1.setText("batal");
        batalBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtn1ActionPerformed(evt);
            }
        });

        panelRound3.setBackground(new java.awt.Color(48, 81, 90));
        panelRound3.setForeground(new java.awt.Color(121, 214, 168));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);
        panelRound3.setRoundTopLeft(10);
        panelRound3.setRoundTopRight(10);

        jLabel5.setFont(new java.awt.Font("Clarendon Blk BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 233, 201));
        jLabel5.setText("Detail Menu");

        jLabel6.setFont(new java.awt.Font("Clarendon Blk BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(252, 233, 201));
        jLabel6.setText("Nama Menu       :");

        jLabel8.setFont(new java.awt.Font("Clarendon Blk BT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(252, 233, 201));
        jLabel8.setText("Harga                :");

        jLabel7.setFont(new java.awt.Font("Clarendon Blk BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(252, 233, 201));
        jLabel7.setText("Deskripsi Menu :");

        deskripsiMenuField.setBackground(new java.awt.Color(48, 81, 90));
        deskripsiMenuField.setColumns(5);
        deskripsiMenuField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        deskripsiMenuField.setForeground(new java.awt.Color(255, 249, 243));
        deskripsiMenuField.setRows(5);
        deskripsiMenuField.setText("asda\nsdas\nasda\nsada");
        deskripsiMenuField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deskripsiMenuField.setCaretColor(new java.awt.Color(210, 210, 210));
        deskripsiMenuField.setDisabledTextColor(new java.awt.Color(210, 210, 210));
        jScrollPane2.setViewportView(deskripsiMenuField);

        hargaMenuField.setBackground(new java.awt.Color(48, 81, 90));
        hargaMenuField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hargaMenuField.setForeground(new java.awt.Color(255, 249, 243));
        hargaMenuField.setText("test");
        hargaMenuField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        namaMenuField.setBackground(new java.awt.Color(48, 81, 90));
        namaMenuField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaMenuField.setForeground(new java.awt.Color(255, 249, 243));
        namaMenuField.setText("test");
        namaMenuField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(namaMenuField))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(hargaMenuField, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namaMenuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaMenuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Minion Pro SmBd", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Input banyak Pesanan");

        bnyakPesananInputField.setBackground(new java.awt.Color(89, 108, 118));
        bnyakPesananInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnyakPesananInputFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(tambahBtn)
                                .addGap(18, 18, 18)
                                .addComponent(batalBtn1)
                                .addGap(22, 22, 22))
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1)))
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnyakPesananInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnyakPesananInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn)
                    .addComponent(batalBtn1))
                .addGap(16, 16, 16))
        );

        editMenuPanel.setRoundBottomLeft(10);
        editMenuPanel.setRoundBottomRight(10);
        editMenuPanel.setRoundTopLeft(10);
        editMenuPanel.setRoundTopRight(10);
        editMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMenuPanelMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setText("LOGOUT");

        javax.swing.GroupLayout editMenuPanelLayout = new javax.swing.GroupLayout(editMenuPanel);
        editMenuPanel.setLayout(editMenuPanelLayout);
        editMenuPanelLayout.setHorizontalGroup(
            editMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editMenuPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18))
        );
        editMenuPanelLayout.setVerticalGroup(
            editMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LabelPembeli.setBackground(new java.awt.Color(89, 108, 118));
        LabelPembeli.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LabelPembeli.setForeground(new java.awt.Color(48, 81, 90));
        LabelPembeli.setText("Transaksi");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LogoUtama.png"))); // NOI18N

        editMenuLabel.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        editMenuLabel.setForeground(new java.awt.Color(48, 81, 90));
        editMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editMenuLabel.setText("Edit Menu");
        editMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMenuLabelMouseClicked(evt);
            }
        });

        riwayatPesananLabel.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        riwayatPesananLabel.setForeground(new java.awt.Color(48, 81, 90));
        riwayatPesananLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        riwayatPesananLabel.setText(" Riwayat Pesanan");
        riwayatPesananLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatPesananLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelPembeli)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(editMenuLabel)
                        .addGap(18, 18, 18)
                        .addComponent(riwayatPesananLabel)
                        .addGap(18, 18, 18)
                        .addComponent(editMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(editMenuLabel)
                                .addComponent(riwayatPesananLabel)
                                .addComponent(LabelPembeli)))
                        .addGap(25, 25, 25))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnyakPesananInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnyakPesananInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnyakPesananInputFieldActionPerformed

    private void tambahPesananBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPesananBtnActionPerformed
        // TODO add your handling code here:
        float sub_total=0;
        List<Menu> tempData = new ArrayList<>();
        TempMenu tempMenu = null;
        Pembeli tempPembeli=null;
        Pesanan tempPesanan=null;
        
        try {
            InputanKosongException();
            
            for (int i = 0; i < tempListMenu.size(); i++){
                sub_total += (tempListMenu.get(i).getHarga_menu()*tempListMenu.get(i).getJumlah_pesanan());
            }

            Pembeli pembeli = new Pembeli(namaPembeliInput.getText(), nomorHPInput.getText());

            pembeliControl.insertPembeli(pembeli);

            tempPembeli = pembeliControl.getLastPembeli();

            Pesanan pesanan = new Pesanan(pegawai.getId(), tempPembeli.getId(), sub_total, tanggalTransaksiInput.getText(),"BELUM DIBAYAR");

            pesananControl.insertDetailPesanan(pesanan);

            for (int i = 0; i < tempListMenu.size(); i++){
                tempData = mc.searchMenu(tempListMenu.get(i).getNama_menu());

                DetailPesanan dp = new DetailPesanan(pesananControl.getLastPesanan().getId(),
                        tempData.get(0),
                        tempListMenu.get(i).getJumlah_pesanan(),
                         (tempListMenu.get(i).getJumlah_pesanan()* tempListMenu.get(i).getHarga_menu()));
                detailControl.insertDetailPesanan(dp);
              
            }
            
            tempListMenu.removeAll(tempListMenu);
            tambahPesananBtn.setEnabled(false);
            batalBtn2.setEnabled(false);
            clearText();
            showMenu();
            JOptionPane.showMessageDialog(this, "Pesanan Berhasil dibuat !");
        } catch (InputanKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        }
        
        
        
       
    }//GEN-LAST:event_tambahPesananBtnActionPerformed

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        // TODO add your handling code here:
        int clickedRow = tblMenu.getSelectedRow();
        List<Menu> tempData = new ArrayList<>();
        TempMenu tempMenu = null;
        
        TableModel tableModel = tblMenu.getModel();
        
        int selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        
        namaMenuField.setText(tableModel.getValueAt(clickedRow, 1).toString());
        hargaMenuField.setText(tableModel.getValueAt(clickedRow, 4).toString());
        deskripsiMenuField.setText(tableModel.getValueAt(clickedRow, 2).toString());
        
        bnyakPesananInputField.setEnabled(true);
        tambahBtn.setEnabled(true);
        batalBtn1.setEnabled(true);
        bnyakPesananInputField.setText("");
        action = "tambah";
        
        // untuk memasukan data yang dipilih ke list menu temp
//        tempData = mc.searchMenu(namaMenuField.getText());
//        count++;
//        tempMenu = new TempMenu(tempData.get(0).getNama_menu(), 
//                tempData.get(0).getHarga_menu(),
//                Integer.parseInt(bnyakPesananInputField.getText()));
//        
//        tempListMenu.add(tempMenu);
//        tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
        
        
        
               
    }//GEN-LAST:event_tblMenuMouseClicked

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
        List<Menu> tempData = new ArrayList<>();
        TempMenu tempMenu = null;
        String check = "tambah";
        
        try {
            NegativeInputException();
            
            tempData = mc.searchMenu(namaMenuField.getText());
            tempMenu = new TempMenu(tempData.get(0).getNama_menu(), 
                    tempData.get(0).getHarga_menu(),
                    Integer.parseInt(bnyakPesananInputField.getText()));
            if (tempListMenu.isEmpty()) {
                tempListMenu.add(tempMenu);
                System.out.println("kosong");
            }else{
                for (int i = 0; i < tempListMenu.size(); i++) {
                if (tempListMenu.get(i).getNama_menu().equals(tempMenu.getNama_menu())&& action.equals("edit")) {
                    tempListMenu.get(i).setJumlah_pesanan(tempMenu.getJumlah_pesanan());
                    check = "update";
                    System.out.println(check);
                    break;
                }else if (tempListMenu.get(i).getNama_menu().equals(tempMenu.getNama_menu())&& action.equals("tambah")) {
                    tempListMenu.get(i).setJumlah_pesanan(tempMenu.getJumlah_pesanan()+tempListMenu.get(i).getJumlah_pesanan());
                    check= "update";
                    break;
                }

                }
                if (!check.equals("update") ) {
                    tempListMenu.add(tempMenu);
                }
            }

        } catch (NegativeInputException e) {
            JOptionPane.showMessageDialog(this, "Banyak pesanan harus lebih dari 0");
        }
        
        
        
        
        // tambah fitur hapus temp  menu???
       
        
        tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
        clearInputMenu();
        tambahPesananBtn.setEnabled(true);
        batalBtn2.setEnabled(true);
        tambahBtn.setEnabled(false);
        batalBtn1.setEnabled(false);
        bnyakPesananInputField.setEnabled(false);
        
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void editMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuLabelMouseClicked
        // klik panel edit menu
        MenuView mv = new MenuView(pegawai);
        this.dispose();
        mv.setVisible(true);
    }//GEN-LAST:event_editMenuLabelMouseClicked

    private void riwayatPesananLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatPesananLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatPesananLabelMouseClicked

    private void tblTempMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTempMenuMouseClicked
        // TODO add your handling code here:
        int clickedRow = tblTempMenu.getSelectedRow();
        List<Menu> tempData = new ArrayList<>();
        Menu menu = null;
        
        TableModel tableModel = tblTempMenu.getModel();
        
        tempData = mc.searchMenu(tableModel.getValueAt(clickedRow, 1).toString());
        menu = new Menu(tempData.get(0).getNama_menu(),
                tempData.get(0).getDeskripsi_menu(),
                tempData.get(0).getKategori(),
                tempData.get(0).getHarga_menu());
        
        
        
        namaMenuField.setText(menu.getNama_menu());
        hargaMenuField.setText(Integer.toString(menu.getHarga_menu()));
        deskripsiMenuField.setText(menu.getDeskripsi_menu());
        bnyakPesananInputField.setText(tblTempMenu.getValueAt(clickedRow, 2).toString());
        hapusPesananBtn.setEnabled(true);
        bnyakPesananInputField.setEnabled(true);
        tambahBtn.setEnabled(true);
        batalBtn1.setEnabled(true);
        action = "edit";
        
    }//GEN-LAST:event_tblTempMenuMouseClicked

    private void hapusPesananBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPesananBtnActionPerformed
        // TODO add your handling code here:
        int clickedRow = tblTempMenu.getSelectedRow();
        List<Menu> tempData = new ArrayList<>();
        Menu menu = null;
        
        TableModel tableModel = tblTempMenu.getModel();
        
        tempData = mc.searchMenu(tableModel.getValueAt(clickedRow, 1).toString());
        
        if (tempListMenu.size() > 1) {
            for (int i = 0; i < tempListMenu.size(); i++) {
            if (tempListMenu.get(i).getNama_menu().equals(tempData.get(0).getNama_menu())) {
                tempListMenu.remove(i);
                break;
            }
         
            }
        }else{
            tempListMenu.remove(0);
            tambahPesananBtn.setEnabled(false);
        }
        tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
        hapusPesananBtn.setEnabled(false);
    }//GEN-LAST:event_hapusPesananBtnActionPerformed

    private void namaPembeliInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPembeliInputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaPembeliInputActionPerformed

    private void batalBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtn1ActionPerformed
        // TODO add your handling code here:
        namaMenuField.setText("");
        hargaMenuField.setText("");
        deskripsiMenuField.setText("");
        bnyakPesananInputField.setText("");
        bnyakPesananInputField.setEnabled(false);
        tambahBtn.setEnabled(false);
        batalBtn1.setEnabled(false);
        
    }//GEN-LAST:event_batalBtn1ActionPerformed

    private void batalBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtn2ActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Apakah yakin ingin membatalkan pesanan ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(getAnswer == JOptionPane.YES_OPTION){
             tempListMenu.removeAll(tempListMenu);
             tambahPesananBtn.setEnabled(false);
             batalBtn2.setEnabled(false);
             clearText();
             tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
        }else{
            JOptionPane.showMessageDialog(null, "Pesanan tidak jadi dibatalkan!");
        }
       
    }//GEN-LAST:event_batalBtn2ActionPerformed

    private void editMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuPanelMouseClicked
        // klik panel edit menu
        MenuView mv = new MenuView(pegawai);
        this.dispose();
        mv.setVisible(true);
    }//GEN-LAST:event_editMenuPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesananView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPembeli;
    private javax.swing.JButton batalBtn1;
    private javax.swing.JButton batalBtn2;
    private javax.swing.JTextField bnyakPesananInputField;
    private javax.swing.JTextArea deskripsiMenuField;
    private javax.swing.JLabel editMenuLabel;
    private view.PanelRound editMenuPanel;
    private javax.swing.JButton hapusPesananBtn;
    private javax.swing.JTextField hargaMenuField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namaMenuField;
    private javax.swing.JTextField namaPembeliInput;
    private javax.swing.JTextField nomorHPInput;
    private view.PanelRound panelRound1;
    private view.PanelRound panelRound2;
    private view.PanelRound panelRound3;
    private view.PanelRound panelRound4;
    private view.PanelRound panelRound5;
    private javax.swing.JLabel riwayatPesananLabel;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton tambahPesananBtn;
    private javax.swing.JTextField tanggalTransaksiInput;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblTempMenu;
    // End of variables declaration//GEN-END:variables
}
