/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.MenuControl;
import control.PembeliControl;
import control.PesananControl;
import control.DetailPesananControl;
import exception.InputanKosongException;
import exception.NegativeInputException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Menu;
import model.TempMenu;
import model.DetailPesanan;
import model.Pegawai;
import model.Pembeli;
import model.Pesanan;

import table.TableMenu;
import table.TableTempMenu;

public class PesananView extends javax.swing.JFrame {
    private int count=0;
    private MenuControl mc;
    private PembeliControl pembeliControl;
    private PesananControl pesananControl;
    private Pegawai pegawai;
    private DetailPesananControl detailControl;
    private int id_pegawai =1;
    String action = null;
    List<Menu> listMenu;
    List<TempMenu> tempListMenu = new ArrayList<>();
    
    
    
    public PesananView() {
        initComponents();
        mc = new MenuControl();
        pembeliControl = new PembeliControl();
        pesananControl = new PesananControl();
        detailControl = new DetailPesananControl();
        showMenu();
        clearText();
        
    }
    
    public PesananView(Pegawai pegawai) {
        initComponents();
        mc = new MenuControl();
        pembeliControl = new PembeliControl();
        pesananControl = new PesananControl();
        detailControl = new DetailPesananControl();
        this.pegawai = pegawai;
        showMenu();
        clearText();
        setComponent(false);
        
    }
    
    public void showMenu(){
        tblMenu.setModel(mc.showDataMenu(""));
        tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
    }
    
    public void clearDetailMenu(){
        namaMenuField.setText("");
        hargaMenuField.setText("");
        deskripsiMenuField.setText("");
        bnyakPesananInputField.setText("");
    }
    
    public void setComponent(boolean value){
        bnyakPesananInputField.setEnabled(value);
        tambahBtn.setEnabled(value);
        batalBtn1.setEnabled(value);
        tambahPesananBtn.setEnabled(value);
        hapusPesananBtn.setEnabled(value);
        batalBtn2.setEnabled(value);
    }
    
    public void clearText(){
        namaMenuField.setText("");
        hargaMenuField.setText("");
        deskripsiMenuField.setText("");
        bnyakPesananInputField.setText("");
        namaPembeliInput.setText("");
        nomorHPInput.setText("");
        tanggalTransaksiInput.setText("");
    }
    
    public void clearInputMenu(){
        namaMenuField.setText("");
        hargaMenuField.setText("");
        deskripsiMenuField.setText("");
        bnyakPesananInputField.setText("");
    }
    
    public void InputanKosongException() throws InputanKosongException{
        if(namaPembeliInput.getText().isEmpty() 
                    || nomorHPInput.getText().isEmpty() || tanggalTransaksiInput.getText().isEmpty()) {
            throw new InputanKosongException();
        }
    }
    
    public void NegativeInputException() throws NegativeInputException {
        if( Integer.parseInt(bnyakPesananInputField.getText()) <= 0){
            throw new NegativeInputException();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        panelRound1 = new view.PanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTempMenu = new javax.swing.JTable();
        tambahPesananBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        batalBtn2 = new javax.swing.JButton();
        hapusPesananBtn = new javax.swing.JButton();
        panelRound2 = new view.PanelRound();
        panelRound7 = new view.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        namaPembeliInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomorHPInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tanggalTransaksiInput = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        panelRound4 = new view.PanelRound();
        tambahBtn = new javax.swing.JButton();
        batalBtn1 = new javax.swing.JButton();
        panelRound3 = new view.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bnyakPesananInputField = new javax.swing.JTextField();
        namaMenuField = new javax.swing.JLabel();
        hargaMenuField = new javax.swing.JLabel();
        deskripsiMenuField = new javax.swing.JLabel();
        panelRound5 = new view.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        panelRound8 = new view.PanelRound();
        LabelTransaksi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        editMenuLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        riwayatPesananLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pembayaranLabel = new javax.swing.JLabel();
        logoutPanel = new view.PanelRound();
        logoutLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(242, 217, 99));
        mainPanel.setForeground(new java.awt.Color(0, 0, 0));

        panelRound1.setBackground(new java.awt.Color(81, 175, 157));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);

        tblTempMenu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tblTempMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTempMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTempMenuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTempMenu);

        tambahPesananBtn.setBackground(new java.awt.Color(243, 161, 97));
        tambahPesananBtn.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        tambahPesananBtn.setForeground(new java.awt.Color(48, 81, 90));
        tambahPesananBtn.setText("Tambah Pesanan");
        tambahPesananBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPesananBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(48, 81, 90));
        jLabel10.setText("Pesanan Sementara");

        batalBtn2.setBackground(new java.awt.Color(252, 233, 201));
        batalBtn2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        batalBtn2.setForeground(new java.awt.Color(48, 81, 90));
        batalBtn2.setText("Batal");
        batalBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtn2ActionPerformed(evt);
            }
        });

        hapusPesananBtn.setBackground(new java.awt.Color(239, 50, 64));
        hapusPesananBtn.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        hapusPesananBtn.setForeground(new java.awt.Color(252, 233, 201));
        hapusPesananBtn.setText("Hapus Pesanan");
        hapusPesananBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPesananBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hapusPesananBtn)
                                    .addGroup(panelRound1Layout.createSequentialGroup()
                                        .addComponent(tambahPesananBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(batalBtn2)))))
                        .addGap(22, 22, 22))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusPesananBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahPesananBtn)
                    .addComponent(batalBtn2))
                .addGap(18, 18, 18))
        );

        panelRound2.setBackground(new java.awt.Color(81, 175, 157));
        panelRound2.setRoundBottomLeft(15);
        panelRound2.setRoundBottomRight(15);
        panelRound2.setRoundTopLeft(15);
        panelRound2.setRoundTopRight(15);

        panelRound7.setBackground(new java.awt.Color(48, 81, 90));
        panelRound7.setRoundBottomLeft(10);
        panelRound7.setRoundBottomRight(10);
        panelRound7.setRoundTopLeft(10);
        panelRound7.setRoundTopRight(10);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 233, 201));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nama Pembeli");

        namaPembeliInput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        namaPembeliInput.setForeground(new java.awt.Color(48, 81, 90));
        namaPembeliInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        namaPembeliInput.setCaretColor(new java.awt.Color(243, 161, 97));
        namaPembeliInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPembeliInputActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 233, 201));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nomor HP");

        nomorHPInput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nomorHPInput.setForeground(new java.awt.Color(48, 81, 90));
        nomorHPInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 233, 201));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tanggal Transaksi");

        tanggalTransaksiInput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tanggalTransaksiInput.setForeground(new java.awt.Color(48, 81, 90));
        tanggalTransaksiInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(252, 233, 201));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("INPUT PEMBELI");

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorHPInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tanggalTransaksiInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaPembeliInput, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPembeliInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomorHPInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalTransaksiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panelRound4.setBackground(new java.awt.Color(81, 175, 157));
        panelRound4.setForeground(new java.awt.Color(89, 108, 118));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);

        tambahBtn.setBackground(new java.awt.Color(243, 161, 97));
        tambahBtn.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        tambahBtn.setForeground(new java.awt.Color(48, 81, 90));
        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        batalBtn1.setBackground(new java.awt.Color(252, 233, 201));
        batalBtn1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        batalBtn1.setForeground(new java.awt.Color(48, 81, 90));
        batalBtn1.setText("Batal");
        batalBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtn1ActionPerformed(evt);
            }
        });

        panelRound3.setBackground(new java.awt.Color(48, 81, 90));
        panelRound3.setForeground(new java.awt.Color(121, 214, 168));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);
        panelRound3.setRoundTopLeft(10);
        panelRound3.setRoundTopRight(10);

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 233, 201));
        jLabel5.setText("Detail Menu");

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(252, 233, 201));
        jLabel6.setText("Nama Menu       :");

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(252, 233, 201));
        jLabel8.setText("Harga                 :");

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(252, 233, 201));
        jLabel7.setText("Deskripsi Menu :");

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(252, 233, 201));
        jLabel9.setText("Input banyak Pesanan");

        bnyakPesananInputField.setBackground(new java.awt.Color(89, 108, 118));
        bnyakPesananInputField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bnyakPesananInputField.setForeground(new java.awt.Color(48, 81, 90));
        bnyakPesananInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnyakPesananInputFieldActionPerformed(evt);
            }
        });

        namaMenuField.setBackground(new java.awt.Color(252, 233, 201));
        namaMenuField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        namaMenuField.setForeground(new java.awt.Color(252, 233, 201));

        hargaMenuField.setBackground(new java.awt.Color(252, 233, 201));
        hargaMenuField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        hargaMenuField.setForeground(new java.awt.Color(252, 233, 201));

        deskripsiMenuField.setBackground(new java.awt.Color(252, 233, 201));
        deskripsiMenuField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        deskripsiMenuField.setForeground(new java.awt.Color(252, 233, 201));

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(bnyakPesananInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaMenuField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hargaMenuField, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(deskripsiMenuField, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaMenuField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaMenuField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(deskripsiMenuField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bnyakPesananInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelRound5.setBackground(new java.awt.Color(48, 81, 90));
        panelRound5.setRoundBottomLeft(7);
        panelRound5.setRoundBottomRight(7);
        panelRound5.setRoundTopLeft(7);
        panelRound5.setRoundTopRight(7);

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 233, 201));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MENU");

        tblMenu.setBackground(new java.awt.Color(48, 81, 90));
        tblMenu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tblMenu.setForeground(new java.awt.Color(252, 233, 201));
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1)
                .addGap(15, 15, 15))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tambahBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batalBtn1))
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound4Layout.createSequentialGroup()
                                .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addGap(19, 19, 19))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahBtn)
                    .addComponent(batalBtn1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LogoUtama.png"))); // NOI18N

        panelRound8.setBackground(new java.awt.Color(242, 217, 99));

        LabelTransaksi.setBackground(new java.awt.Color(0, 0, 0));
        LabelTransaksi.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        LabelTransaksi.setForeground(new java.awt.Color(81, 175, 157));
        LabelTransaksi.setText("Transaksi");
        LabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelTransaksiMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(48, 81, 90));
        jPanel3.setForeground(new java.awt.Color(81, 175, 157));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        editMenuLabel.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        editMenuLabel.setForeground(new java.awt.Color(48, 81, 90));
        editMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editMenuLabel.setText("Edit Menu");
        editMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMenuLabelMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(48, 81, 90));
        jPanel1.setForeground(new java.awt.Color(81, 175, 157));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        riwayatPesananLabel.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        riwayatPesananLabel.setForeground(new java.awt.Color(48, 81, 90));
        riwayatPesananLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        riwayatPesananLabel.setText(" Riwayat Pesanan");
        riwayatPesananLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatPesananLabelMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(48, 81, 90));
        jPanel2.setForeground(new java.awt.Color(81, 175, 157));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pembayaranLabel.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        pembayaranLabel.setForeground(new java.awt.Color(48, 81, 90));
        pembayaranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pembayaranLabel.setText("Pembayaran");
        pembayaranLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembayaranLabelMouseClicked(evt);
            }
        });

        logoutPanel.setBackground(new java.awt.Color(239, 50, 64));
        logoutPanel.setRoundBottomLeft(10);
        logoutPanel.setRoundBottomRight(10);
        logoutPanel.setRoundTopLeft(10);
        logoutPanel.setRoundTopRight(10);
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(252, 233, 201));
        logoutLabel.setText("LOGOUT");

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addGap(18, 18, 18))
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(riwayatPesananLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembayaranLabel)
                .addGap(18, 18, 18)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editMenuLabel)
                        .addComponent(riwayatPesananLabel)
                        .addComponent(LabelTransaksi)
                        .addComponent(pembayaranLabel))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(panelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel11)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnyakPesananInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnyakPesananInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnyakPesananInputFieldActionPerformed

    private void tambahPesananBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPesananBtnActionPerformed
        // TODO add your handling code here:
        float sub_total=0;
        List<Menu> tempData = new ArrayList<>();
        TempMenu tempMenu = null;
        Pembeli tempPembeli=null;
        Pesanan tempPesanan=null;
        
        try {
            InputanKosongException();
            
            for (int i = 0; i < tempListMenu.size(); i++){
                sub_total += (tempListMenu.get(i).getHarga_menu()*tempListMenu.get(i).getJumlah_pesanan());
            }

            Pembeli pembeli = new Pembeli(namaPembeliInput.getText(), nomorHPInput.getText());

            pembeliControl.insertPembeli(pembeli);

            tempPembeli = pembeliControl.getLastPembeli();
            
            Pesanan pesanan = new Pesanan(pegawai.getId(), tempPembeli.getId(), sub_total, tanggalTransaksiInput.getText(),"BELUM DIBAYAR");

            pesananControl.insertDetailPesanan(pesanan);

            for (int i = 0; i < tempListMenu.size(); i++){
                tempData = mc.searchMenu(tempListMenu.get(i).getNama_menu());

                DetailPesanan dp = new DetailPesanan(pesananControl.getLastPesanan().getId(),
                        tempData.get(0),
                        tempListMenu.get(i).getJumlah_pesanan(),
                         (tempListMenu.get(i).getJumlah_pesanan()* tempListMenu.get(i).getHarga_menu()));
                detailControl.insertDetailPesanan(dp);
              
            }
            
            tempListMenu.removeAll(tempListMenu);
            tambahPesananBtn.setEnabled(false);
            batalBtn2.setEnabled(false);
            clearText();
            showMenu();
            JOptionPane.showMessageDialog(this, "Pesanan Berhasil dibuat !");
        } catch (InputanKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        } 
        
        
        
       
    }//GEN-LAST:event_tambahPesananBtnActionPerformed

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        // TODO add your handling code here:
        int clickedRow = tblMenu.getSelectedRow();
        List<Menu> tempData = new ArrayList<>();
        TempMenu tempMenu = null;
        
        TableModel tableModel = tblMenu.getModel();
        
        int selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        
        namaMenuField.setText(tableModel.getValueAt(clickedRow, 1).toString());
        namaMenuField.setForeground(new java.awt.Color(252, 233, 201));
        hargaMenuField.setText(tableModel.getValueAt(clickedRow, 4).toString());
        deskripsiMenuField.setText(tableModel.getValueAt(clickedRow, 2).toString());
        
        bnyakPesananInputField.setEnabled(true);
        tambahBtn.setEnabled(true);
        batalBtn1.setEnabled(true);
        bnyakPesananInputField.setText("");
        action = "tambah";
        
        // untuk memasukan data yang dipilih ke list menu temp
//        tempData = mc.searchMenu(namaMenuField.getText());
//        count++;
//        tempMenu = new TempMenu(tempData.get(0).getNama_menu(), 
//                tempData.get(0).getHarga_menu(),
//                Integer.parseInt(bnyakPesananInputField.getText()));
//        
//        tempListMenu.add(tempMenu);
//        tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
        
        
        
               
    }//GEN-LAST:event_tblMenuMouseClicked

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
        List<Menu> tempData = new ArrayList<>();
        TempMenu tempMenu = null;
        String check="";
        
        try {
            NegativeInputException();
            
            tempData = mc.searchMenu(namaMenuField.getText());
            tempMenu = new TempMenu(tempData.get(0).getNama_menu(), 
                    tempData.get(0).getHarga_menu(),
                    Integer.parseInt(bnyakPesananInputField.getText()));
            if (tempListMenu.isEmpty()) {
                tempListMenu.add(tempMenu);
                System.out.println("kosong");
            }else{
                for (int i = 0; i < tempListMenu.size(); i++) {
                if (tempListMenu.get(i).getNama_menu().equals(tempMenu.getNama_menu())&& action.equals("edit")) {
                    tempListMenu.get(i).setJumlah_pesanan(tempMenu.getJumlah_pesanan());
                    check = "update";
                    System.out.println(check);
                    break;
                }else if (tempListMenu.get(i).getNama_menu().equals(tempMenu.getNama_menu())&& action.equals("tambah")) {
                    tempListMenu.get(i).setJumlah_pesanan(tempMenu.getJumlah_pesanan()+tempListMenu.get(i).getJumlah_pesanan());
                    check= "update";
                    break;
                }

                }
                if (!check.equals("update")) {
                    tempListMenu.add(tempMenu);
                }
            }

        } catch (NegativeInputException e) {
            JOptionPane.showMessageDialog(this, "Banyak pesanan harus lebih dari 0");
        }  catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Inputan Harus Berupa Angka");
        }
        
        
        
        
        // tambah fitur hapus temp  menu???
       
        
        tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
        clearInputMenu();
        tambahPesananBtn.setEnabled(true);
        batalBtn2.setEnabled(true);
        tambahBtn.setEnabled(false);
        batalBtn1.setEnabled(false);
        bnyakPesananInputField.setEnabled(false);
        
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void editMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuLabelMouseClicked
        // klik panel edit menu
        MenuView mv = new MenuView(pegawai);
        this.dispose();
        mv.setVisible(true);
    }//GEN-LAST:event_editMenuLabelMouseClicked

    private void riwayatPesananLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatPesananLabelMouseClicked
        // TODO add your handling code here:
        HistoryView hv = new HistoryView(pegawai);
        this.dispose();
        hv.setVisible(true);
    }//GEN-LAST:event_riwayatPesananLabelMouseClicked

    private void tblTempMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTempMenuMouseClicked
        // TODO add your handling code here:
        int clickedRow = tblTempMenu.getSelectedRow();
        List<Menu> tempData = new ArrayList<>();
        Menu menu = null;
        
        TableModel tableModel = tblTempMenu.getModel();
        
        tempData = mc.searchMenu(tableModel.getValueAt(clickedRow, 0).toString());
        menu = new Menu(tempData.get(0).getNama_menu(),
                tempData.get(0).getDeskripsi_menu(),
                tempData.get(0).getKategori(),
                tempData.get(0).getHarga_menu());
        
        
        
        namaMenuField.setText(menu.getNama_menu());
        hargaMenuField.setText(Integer.toString(menu.getHarga_menu()));
        deskripsiMenuField.setText(menu.getDeskripsi_menu());
        bnyakPesananInputField.setText(tblTempMenu.getValueAt(clickedRow, 2).toString());
        hapusPesananBtn.setEnabled(true);
        bnyakPesananInputField.setEnabled(true);
        tambahBtn.setEnabled(true);
        batalBtn1.setEnabled(true);
        action = "edit";
        
    }//GEN-LAST:event_tblTempMenuMouseClicked

    private void hapusPesananBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPesananBtnActionPerformed
        // TODO add your handling code here:
        int clickedRow = tblTempMenu.getSelectedRow();
        List<Menu> tempData = new ArrayList<>();
        Menu menu = null;
        
        TableModel tableModel = tblTempMenu.getModel();
        
        tempData = mc.searchMenu(tableModel.getValueAt(clickedRow, 0).toString());
        
        if (tempListMenu.size() > 1) {
            for (int i = 0; i < tempListMenu.size(); i++) {
            if (tempListMenu.get(i).getNama_menu().equals(tempData.get(0).getNama_menu())) {
                tempListMenu.remove(i);
                break;
            }
         
            }
        }else{
            tempListMenu.remove(0);
            tambahPesananBtn.setEnabled(false);
        }
        tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
        
        hapusPesananBtn.setEnabled(false);
        tambahBtn.setEnabled(false);
        batalBtn1.setEnabled(false);
        clearDetailMenu();
    }//GEN-LAST:event_hapusPesananBtnActionPerformed

    private void namaPembeliInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPembeliInputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaPembeliInputActionPerformed

    private void batalBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtn1ActionPerformed
        // TODO add your handling code here:
        clearDetailMenu();
        bnyakPesananInputField.setEnabled(false);
        tambahBtn.setEnabled(false);
        batalBtn1.setEnabled(false);
        
    }//GEN-LAST:event_batalBtn1ActionPerformed

    private void batalBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtn2ActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Apakah yakin ingin membatalkan pesanan ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(getAnswer == JOptionPane.YES_OPTION){
             tempListMenu.removeAll(tempListMenu);
             tambahPesananBtn.setEnabled(false);
             batalBtn2.setEnabled(false);
             clearText();
             tblTempMenu.setModel(mc.showTempMenu(tempListMenu));
        }else{
            JOptionPane.showMessageDialog(null, "Pesanan tidak jadi dibatalkan!");
        }
       
    }//GEN-LAST:event_batalBtn2ActionPerformed

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // klik panel edit menu
        LoginView lv = new LoginView();
        this.dispose();
        lv.setVisible(true);
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void pembayaranLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembayaranLabelMouseClicked
        // TODO add your handling code here:
        PembayaranView lv = new PembayaranView(pegawai);
        this.dispose();
        lv.setVisible(true);
    }//GEN-LAST:event_pembayaranLabelMouseClicked

    private void LabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelTransaksiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LabelTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesananView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTransaksi;
    private javax.swing.JButton batalBtn1;
    private javax.swing.JButton batalBtn2;
    private javax.swing.JTextField bnyakPesananInputField;
    private javax.swing.JLabel deskripsiMenuField;
    private javax.swing.JLabel editMenuLabel;
    private javax.swing.JButton hapusPesananBtn;
    private javax.swing.JLabel hargaMenuField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logoutLabel;
    private view.PanelRound logoutPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaMenuField;
    private javax.swing.JTextField namaPembeliInput;
    private javax.swing.JTextField nomorHPInput;
    private view.PanelRound panelRound1;
    private view.PanelRound panelRound2;
    private view.PanelRound panelRound3;
    private view.PanelRound panelRound4;
    private view.PanelRound panelRound5;
    private view.PanelRound panelRound7;
    private view.PanelRound panelRound8;
    private javax.swing.JLabel pembayaranLabel;
    private javax.swing.JLabel riwayatPesananLabel;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton tambahPesananBtn;
    private javax.swing.JTextField tanggalTransaksiInput;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblTempMenu;
    // End of variables declaration//GEN-END:variables
}
